# Generated by Django 2.1.7 on 2021-08-18 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmarked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbyuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='draftblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=500)),
                ('dsummary', models.CharField(max_length=3000)),
                ('dcontent', models.TextField()),
                ('dai_generated_summary', models.TextField()),
                ('dimage1', models.ImageField(upload_to='media/dblog')),
                ('dimage2', models.ImageField(upload_to='media/dblog')),
                ('dimage3', models.ImageField(upload_to='media/dblog')),
                ('dtags', models.CharField(max_length=3000)),
                ('dbyuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.User_profileing')),
            ],
        ),
        migrations.CreateModel(
            name='publishedblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=3000)),
                ('content', models.TextField()),
                ('ai_generated_summary', models.TextField()),
                ('image1', models.ImageField(upload_to='media/pblog')),
                ('image2', models.ImageField(upload_to='media/pblog')),
                ('image3', models.ImageField(upload_to='media/pblog')),
                ('tags', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('byuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.User_profileing')),
            ],
        ),
        migrations.AddField(
            model_name='bookmarked',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.publishedblog'),
        ),
    ]
